### ISSUE TITLE
Access clients by associative array

### ISSUE THREAD

**Issue by p810** [Kitsune-/Kitsune#12]
Problem
=======

Currently the way we find a specific client is like so:

```php
foreach($server->penguins as $penguin) {
  if($penguin->name == $arbitraryUsername) {
    # ...
  }
}
```

**Kitsune.php** handles the addition of new clients. We can see on [line #15](https://github.com/Kitsune-/Kitsune/blob/8f6cb96d2dc31a24326c4ad9592e7c634fac58fd/Kitsune/Kitsune.php#L15) that a client is added to the array by its resource. This makes it so that iteration is required for finding a client who is not the one represented by the connection.

Solution
======

I propose that a client be stored by either his/her username or ID for faster look up, and to use array_key_exists() for checking whether a user exists in the array. 

```php
if(!array_key_exists($nameOrID, $server->penguins) {
  return false;
}

# ...
```

Reasoning
========

I did a simple time test of three ways we could find whether a client is active:

1. array_key_exists()
2. foreach() iteration
3. array_search()

Each test ran ten times. There were some variances, likely due to my machine, so I took the mean value of each ten results and compared:

array_key_exists() | foreach() | array_search()
------------------------- | ------------ | ---------------------
1.978874206543E-6 | 2.281665802002E-5 | 1.0967254638672E-6

These trials were then again run about five times. The variances make it hard to tell what exactly is the most efficient (perhaps I'll run this through xdebug too), ~~but it seemed to be that array_key_exists() and accessing it by the key was the fastest.~~

I proposed that method also because it is the simplest. Rather than having to perform an iteration, or finding the value, returning the key, and assigning it to a local variable, we simply check if the client is online, and then access their data.

**Comment by TunnelBlanket** [comment]
Implemented.
