### ISSUE TITLE
Casting int instead of using function intval() 

### ISSUE THREAD

**Issue by Romtoc** [Kitsune-/Kitsune#30]
Using <code>(int)$var</code> is faster than <code>intval($var)</code>

In this case, you seem to be using <code>intval()</code> in things like:

<code>$open = intval(isset($this->openIgloos[$playerId]));</code>

Another alternative is to use the <code>?</code> operator.

<code>isset($var) ? 1 : 0;</code>

**Comment by Elixur** [comment]
Do you have any benchmark tests for proof? Kind of interested.

**Comment by Romtoc** [comment]
Hi Shawn, glad atleast you're taking it into consideration, even its a small difference I definitely think you should make the necessary changes http://stackoverflow.com/questions/239136/fastest-way-to-convert-string-to-integer-in-php

**Comment by Elixur** [comment]
I'm not Shawn, I'm Cal/Swanky, haha. I'll keep this noted for the future.

**Comment by JarRawr** [comment]
Something to note about the benchmarks provided in the stackoverflow link give, the accepted answers benchmarks were posted in 2008(and possibly updated in 2010) and there has since been several new PHP versions.

**Comment by TunnelBlanket** [comment]
I've already committed to changes to my local repository. They should be live by Friday.
