### ISSUE TITLE
Wrong Errors - Owned Floor, Location

### ISSUE THREAD

**Issue by Romtoc** [Kitsune-/Kitsune#32]
In <code>Igloo.php</code>, the errors being sent for owned floor, location are wrong.

<code>
elseif(isset($penguin->locations[$locationId])) {
			return $penguin->send("%xt%e%-1%400%");
		}
</code>

<code>
elseif(isset($penguin->floors[$floorId])) {
			return $penguin->send("%xt%e%-1%400%");
		}
</code>

The correct errors are:

- Floor: 501
- Location: 502

**Comment by TunnelBlanket** [comment]
Will push soon.
