### ISSUE TITLE
Puffle Bug Fix.

### ISSUE THREAD

**Issue by valid22** [Kitsune-/Kitsune#33]
In Penguin.php
From line 404 - 409.
It is:
```
if(!empty($this->walkingPuffle)) {
			list($id, $type, $subtype, $hat) = $this->walkingPuffle;
			array_push($player, $id, $type, $subtype, $hat, 0,); // 19->23 


```

So, Below that adding
```
			
		}
		else {
			array_push($player, 0)
		}

```
Will fix that issue ;)

So the full code will be

```

if(!empty($this->walkingPuffle)) {
			list($id, $type, $subtype, $hat) = $this->walkingPuffle;
			array_push($player, $id, $type, $subtype, $hat, 0,$this->database->getGlows($this->id, 'ALL')); // 19->23 then 24->33 );
			
		}
		else {
			array_push($player, 0)
		}


```

And Above that.

in player array, Between Avatar and AvatarArray. Adding a null byte(0) will fix this full issue!

so,
```
$this->avatar,
0, //Null Byte!!
$this->avatarAttributies

```

**Comment by Elixur** [comment]
Do you have screenshots of this working? I'm not able to test this myself.

**Comment by valid22** [comment]
Yes, uPlayEve and for others all. My Localhost have no Puffle.

**Comment by TunnelBlanket** [comment]
I didn't experience the blue puffle bug after applying this fix to Kitsune (which was done locally), but after logging out then back in, my puffle was gone. That probably doesn't have anything to do with this issue (meaning that it's probably it's own thing), but I'd still like to fix it.

Any ideas?

**Comment by valid22** [comment]
Yeah! The packets on Net are old packets, Cp's new client uses packets new, We'll use old Incomplete packets. And, We have fixed this issue on uPlayEve by that method !!

**Comment by Elixur** [comment]
TunnelBlanket, we've had that issue for a while. If you log out your puffle doesn't return to your igloo, it just disappears, but if you leave your puffle in your igloo it'll stay. I forgot how I fixed it, I think I just used the packet to send the walking puffle to your igloo(I think?) if the penguin is removed, but I'm not 100% sure if that's what I did.. you can try that.

**Comment by TunnelBlanket** [comment]
@valid22 this has nothing to do with furniture
@Elixur figured

**Comment by valid22** [comment]
Ok.But my packets makes the puffle stay at your hand :wink: . Mainly adding A null byte! Anyway , Please release that fix!
