### ISSUE TITLE
Stamps at the end of a game are not showing

### ISSUE THREAD

**Issue by Anoname** [Kitsune-/Kitsune#37]
When you win stamps in pizzatron, for exemple, it doesnt show a prompt with how much stamps you have for the game ect....

Exemple :
http://clubpenguincp.com/images/2010/07/chrispage5.jpg

Maybe something is wrong in : 
https://github.com/Kitsune-/Kitsune/blob/master/Kitsune/ClubPenguin/Handlers/Game/General.php

Sorry if i have a bad english, if you dont understand...

**Comment by TunnelBlanket** [comment]
I'll look into it. Thank you.

**Comment by Anoname** [comment]
Thank you.

**Comment by Anoname** [comment]
Sorry, its working, its just because my stamps.json was corrupted.
