### ISSUE TITLE
Server attempts to run non-php files inside plugins directory

### ISSUE THREAD

**Issue by JarRawr** [Kitsune-/Kitsune#5]
I noticed this while working on the plugin database, the server will attempt to run non-php files that are inside the plugins directory causing a fatal error.
Fix: add if(in_array($pluginClass.".php", $pluginFiles)) { above $this->loadPlugin($pluginClass, $pluginNamespace);
http://prntscr.com/4h2qpx

**Comment by TunnelBlanket** [comment]
Fixed.
